//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EDDPia.rc
//
#define WND_LOGIN                       101
#define IDR_MENU1                       105
#define IDD_RPERSONAS                   106
#define IDD_PROPPAGE_LARGE              107
#define IDD_PERSONAS                    108
#define IDD_BORRAR_PERSONA              110
#define IDD_VACUNAS                     112
#define DLG_AGG_VACUNA                  114
#define DLG_BORR_VAC                    116
#define DLG_REGISTRO_USER               118
#define IDD_DIALOG1                     120
#define IDD_CARNET                      120
#define IDD_CARNET_HOME                 122
#define IDD_ALTA_CARNET                 124
#define IDD_EDITARCNT                   126
#define IDD_PRE_EDICION                 129
#define IDD_CARNET_CU                   131
#define IDD_ELIMINAR_CARNET             133
#define IDD_BUSCAR_cARNET               135
#define IDD_BUSCAR_CARNET               135
#define IDD_ORDENAMIENTO                137
#define TXT_USERNAME                    1001
#define BTN_LOGIN                       1003
#define TXT_PASSWORD                    1004
#define DLG_INICIO                      1005
#define IDD_EPERSONAS                   1006
#define DLG_INICIO2                     1006
#define DLG_ED_VACUNA                   1007
#define IDC_NOMBRE_PERSONA              1008
#define IDD_FORMVIEW                    1008
#define IDC_DIRECCION_PERSONA           1010
#define IDC_AM_PERSONA                  1011
#define IDC_CLAVE_UNICA                 1013
#define IDC_LIST1                       1014
#define ID_CANCEL                       1015
#define ID_BTNRP                        1016
#define ID_REGISTRAR_OK                 1017
#define IDC_NOMBRE_HOME                 1018
#define IDC_CLAVE_BORRAR                1019
#define ID_BORRAR_PERSONA               1020
#define BTN_BORRAR_PERSONA              1021
#define BTN_CANCELAR_R                  1022
#define BTN_CANCELAR_BR                 1023
#define IDC_STAT                        1024
#define IDC_BUCAR_CLAVE                 1025
#define IDC_BUSCAR                      1026
#define BTN_EDITAR                      1031
#define ID_EDITAR_OK                    1032
#define BTN_CANCELAR_E                  1033
#define ID_AGREGAR_VACUNAS              1036
#define ID_EDITAR_VACUNAS               1037
#define ID_BORRAR_VACUNAS               1038
#define EB_ED_NOMBRE                    1039
#define EB_ED_CLAVE                     1040
#define EB_V_ED_PRECIO                  1041
#define EB_VED_CDD                      1042
#define EB_VED_DESC                     1043
#define BNT_AGG_VAC                     1044
#define EB_NOM_VAC                      1045
#define EB_CLAVE_VAC                    1046
#define EB_PRECIO_VAC                   1047
#define EB_DOSIS_VAC                    1048
#define EB_DESC_VAC                     1049
#define BTN_CANCEL_BOR                  1050
#define BTN_BORR_VAC                    1051
#define EB_CLAVE_VAC_BR                 1052
#define ID_C_A_VAC                      1053
#define EB_CLAVED_VAC                   1054
#define BTN_BSCR_VAC                    1055
#define BTN_CANCEL_EDVA                 1057
#define BTN_EDITA_VAC                   1058
#define EB_NS_USUARIO                   1059
#define EB_AS_USUARIO                   1060
#define EB_PASS_USUARIO                 1062
#define BTN_LISTO_RE                    1063
#define EB_USER_RE                      1064
#define BTN_REGRESAR_REGS               1065
#define BTN_REGISTRAR_USER              1066
#define ST_ST1                          1067
#define BR_SI                           1068
#define EB_ESTADO                       1070
#define EB_CIUDAD                       1071
#define EB_POSTAL                       1072
#define EB_DIRECCION                    1073
#define EB_E_NOMBRE                     1074
#define EB_E_AP                         1075
#define EB_E_AM                         1076
#define EB_E_ESDO                       1077
#define EB_E_CIUDAD                     1078
#define EB_E_POSTAL                     1079
#define EB_E_DIRECCION                  1080
#define EB_CU_E                         1082
#define RB_SI_E                         1083
#define EB_NO_E                         1084
#define RB_NO                           1085
#define NAME_PRNS                       1086
#define NAME_RP                         1087
#define NAME_BRRAR                      1088
#define NAME_EPS                        1089
#define NAME_VACINI                     1090
#define NAME_AV                         1091
#define NAME_BV                         1092
#define NAME_EV                         1093
#define LISTA_PERSONAS                  1094
#define LISTA_VACUNAS                   1095
#define BTN_FOTOP                       1096
#define BTM_PERSONA                     1100
#define EB_TELEFONO                     1101
#define BTN_DDI                         1103
#define BTM_DDI                         1104
#define CMB_SEXO                        1105
#define DTP_NACIMIENTO                  1106
#define CMB_GOCP                        1107
#define CMB_PRSGO                       1108
#define CMB_VCC                         1109
#define TXT_NAME                        1110
#define TXT_AP                          1111
#define TXT_AM                          1112
#define BTM_FC                          1113
#define BTM_FDC                         1114
#define TXT_FNC                         1115
#define TXT_ID                          1116
#define TXT_PVCC                        1117
#define TXT_SVCC                        1118
#define TXT_TVCC                        1119
#define TXT_CVCC                        1120
#define TXT_VCC                         1121
#define TXT_DRCC                        1122
#define TXT_SX                          1123
#define BTM_EPSNA                       1124
#define BTM_DDI_E                       1125
#define EB_TELEFONO_E                   1126
#define CMB_SEXO_E                      1127
#define DTP_NACIMIENTO_E                1128
#define CMB_GOCP_E                      1129
#define CMB_PRSGO_E                     1130
#define CMB_VCC_E                       1131
#define BTN_DDI_E                       1132
#define BTN_FOTOP_E                     1133
#define BTN_CNT_C                       1134
#define IDC_CARNETS                     1137
#define BTM_CNTR                        1138
#define BTN_CNT_B                       1139
#define BTN_CNT_SR                      1140
#define EB_NM_SR                        1141
#define EB_AP_SR                        1142
#define EB_AM_SR                        1143
#define BTN_CREAR                       1145
#define BTN_CANCELSRCH                  1146
#define DTM_DOSIS                       1147
#define TXT_ESTADO                      1148
#define TXT_CIUDAD                      1149
#define BTN_LISTO_CNT                   1150
#define EB_EN_CTN                       1151
#define EB_EAP_CNT                      1152
#define EB_EAM_CNT                      1153
#define CB_ESX_CNT                      1154
#define DTM_EFN_CNT                     1155
#define EB_EC_CNT                       1157
#define EB_EDC_CNT                      1158
#define CB_EVC_CNT                      1159
#define DTM_EP_CNT                      1160
#define BTN_EF_CNT                      1161
#define BTN_EID_CNT                     1162
#define TXT_ID_E                        1163
#define DTP_ESD_CNT                     1164
#define DTP_ETD_CNT                     1165
#define DTP_ECD_CNT                     1166
#define BTM_FC_E_CU                     1167
#define BTM_FDC_ED                      1168
#define EB_NM_SR_E                      1169
#define EB_AP_SR_E                      1170
#define EB_AM_SR_E                      1171
#define EB_CU_SR_E                      1172
#define BTN_CNTED                       1173
#define BTN_CNCED                       1174
#define BTN_CUC_CNC                     1175
#define BTN_SRCU                        1176
#define EB_NM_SR_ECU                    1177
#define EB_AP_SR_ECU                    1178
#define EB_AM_SR_ECU                    1179
#define EB_CU_SR_ECU                    1180
#define EB_EDO_CTN                      1181
#define BTN_C_ECNT                      1182
#define TXT_CURP_BSED                   1184
#define GB_CU                           1185
#define BTN_CUGENERAR                   1186
#define BTN_BUS_CU                      1187
#define BTN_EDITAR_CANT                 1188
#define EB_ID_ELIM                      1190
#define BTN_BORRAR_CARNET               1191
#define BTN_C_BORRARCNT                 1192
#define EB_BC_NOM                       1193
#define EB_BC_AP                        1194
#define EB_BC_AM                        1195
#define EB_BC_CU                        1196
#define BTN_BC_C_CU                     1197
#define BTN_BUSCAR_CNTPS                1198
#define BTN_CNR_BUS                     1199
#define GB_BC                           1200
#define TXT_BC_CU                       1201
#define IDC_BUTTON1                     1202
#define BTN_HEAPSORT                    1202
#define IDC_BUTTON2                     1204
#define ID_REGISTRO_CARNET              40001
#define ID_REGISTRO_CIUDADANO           40002
#define ID_REGISTRO_VACUNAS             40003
#define MN_CARNET                       40004
#define MN_CIUDADANO                    40005
#define MN_VACUNAS                      40006
#define ID_REPORTES                     40007
#define ID_SALIR_ADAS                   40008
#define MN_SALIR                        40009
#define ID_CIUDADANO_REGISTRAS          40010
#define ID_CIUDADANO_DA                 40011
#define ID_CIUDADANO_EDITAR             40012
#define ID_CIUDADANO_EDITAR40013        40013
#define ID_VACUNAS_INICIO               40014
#define ID_VACUNAS_REGISTRAR            40015
#define ID_VACUNAS_DARDEBAJA            40016
#define ID_VACUNAS_EDITAR               40017
#define ID_CIUDADANO_BAJA               40018
#define MN_INICIO                       40019
#define MN_CIU_BAJA                     40020
#define ID_CARNET_INICIO                40021
#define ID_CARNET_REGISTRAR             40022
#define ID_Menu                         40023
#define ID_CARNET_ELIMINAR              40024
#define ID_CARNET_ELIMINAR40025         40025
#define MN_BUSCAR                       40026
#define MN_SR_CNT                       40027
#define MN_H_GNL                        40028
#define MN_A_CTN                        40029
#define MN_A_CNT                        40030
#define MN_E_CNT                        40031
#define MN_B_CNT                        40032

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         40033
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
